name: CI

on:
  push:
    branches:
      - main
      - feat/github_pipeline
    paths:
    - project/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: main

      # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Display current directory
      run: |
        echo "Current directory: ${{ github.workspace }}"
        ls ${{ github.workspace }}

    - name: Install dependencies
      run: pip install -r project/requirements.txt

    - name: Run tests
      run: bash project/tests.sh
