name: CI

on:
  push:
    branches:
      - main
    paths:
    - project/**
    - .github/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: main

      # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r main/project/requirements.txt

    - name: Run tests
      run: bash main/project/tests.sh
